# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liqinghua/eric/test2/MATRIXWallet.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 918)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 921, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.GenerateA1 = QtWidgets.QPushButton(self.frame)
        self.GenerateA1.setGeometry(QtCore.QRect(670, 50, 111, 51))
        self.GenerateA1.setObjectName("GenerateA1")
        self.ValidatorradioButton = QtWidgets.QRadioButton(self.frame)
        self.ValidatorradioButton.setGeometry(QtCore.QRect(170, 120, 61, 20))
        self.ValidatorradioButton.setObjectName("ValidatorradioButton")
        self.VDepositValue = QtWidgets.QLineEdit(self.frame)
        self.VDepositValue.setGeometry(QtCore.QRect(240, 120, 141, 21))
        self.VDepositValue.setObjectName("VDepositValue")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 51, 21))
        self.label_3.setObjectName("label_3")
        self.WalletAddress = QtWidgets.QLineEdit(self.frame)
        self.WalletAddress.setGeometry(QtCore.QRect(90, 10, 571, 21))
        self.WalletAddress.setObjectName("WalletAddress")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label_10.setObjectName("label_10")
        self.entrustAccount = QtWidgets.QLineEdit(self.frame)
        self.entrustAccount.setGeometry(QtCore.QRect(90, 50, 571, 21))
        self.entrustAccount.setObjectName("entrustAccount")
        self.CloseWallet = QtWidgets.QPushButton(self.frame)
        self.CloseWallet.setGeometry(QtCore.QRect(780, 0, 121, 51))
        self.CloseWallet.setObjectName("CloseWallet")
        self.ConfirmWalletOP = QtWidgets.QPushButton(self.frame)
        self.ConfirmWalletOP.setGeometry(QtCore.QRect(670, 110, 111, 61))
        self.ConfirmWalletOP.setObjectName("ConfirmWalletOP")
        self.OpenWallet = QtWidgets.QPushButton(self.frame)
        self.OpenWallet.setGeometry(QtCore.QRect(670, 0, 111, 51))
        self.OpenWallet.setObjectName("OpenWallet")
        self.AutoCloseWallet = QtWidgets.QCheckBox(self.frame)
        self.AutoCloseWallet.setGeometry(QtCore.QRect(790, 50, 101, 20))
        self.AutoCloseWallet.setObjectName("AutoCloseWallet")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(10, 80, 661, 141))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.Current2Fixed = QtWidgets.QPushButton(self.frame_10)
        self.Current2Fixed.setGeometry(QtCore.QRect(470, 70, 91, 31))
        self.Current2Fixed.setObjectName("Current2Fixed")
        self.FollowSuperNode = QtWidgets.QRadioButton(self.frame_10)
        self.FollowSuperNode.setGeometry(QtCore.QRect(20, 80, 100, 51))
        self.FollowSuperNode.setObjectName("FollowSuperNode")
        self.Fixed3MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed3MradioButton.setGeometry(QtCore.QRect(410, 40, 61, 20))
        self.Fixed3MradioButton.setObjectName("Fixed3MradioButton")
        self.Fixed6MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed6MradioButton.setGeometry(QtCore.QRect(480, 20, 61, 20))
        self.Fixed6MradioButton.setObjectName("Fixed6MradioButton")
        self.CurrentradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.CurrentradioButton.setGeometry(QtCore.QRect(410, 70, 61, 20))
        self.CurrentradioButton.setObjectName("CurrentradioButton")
        self.Deposit = QtWidgets.QPushButton(self.frame_10)
        self.Deposit.setGeometry(QtCore.QRect(570, 10, 81, 41))
        self.Deposit.setObjectName("Deposit")
        self.DecreaseDeposit = QtWidgets.QPushButton(self.frame_10)
        self.DecreaseDeposit.setGeometry(QtCore.QRect(570, 50, 81, 41))
        self.DecreaseDeposit.setObjectName("DecreaseDeposit")
        self.Fixed1MradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed1MradioButton.setGeometry(QtCore.QRect(410, 20, 61, 20))
        self.Fixed1MradioButton.setObjectName("Fixed1MradioButton")
        self.Fixed12Mradiobutton = QtWidgets.QRadioButton(self.frame_10)
        self.Fixed12Mradiobutton.setGeometry(QtCore.QRect(480, 40, 61, 20))
        self.Fixed12Mradiobutton.setObjectName("Fixed12Mradiobutton")
        self.WorkAccount = QtWidgets.QLineEdit(self.frame_10)
        self.WorkAccount.setGeometry(QtCore.QRect(140, 100, 511, 21))
        self.WorkAccount.setObjectName("WorkAccount")
        self.CreateSuperNode = QtWidgets.QRadioButton(self.frame_10)
        self.CreateSuperNode.setGeometry(QtCore.QRect(20, 30, 100, 51))
        self.CreateSuperNode.setObjectName("CreateSuperNode")
        self.NormalNode = QtWidgets.QRadioButton(self.frame_10)
        self.NormalNode.setGeometry(QtCore.QRect(20, 0, 100, 31))
        self.NormalNode.setObjectName("NormalNode")
        self.MDepositValue = QtWidgets.QLineEdit(self.frame_10)
        self.MDepositValue.setGeometry(QtCore.QRect(230, 10, 141, 21))
        self.MDepositValue.setObjectName("MDepositValue")
        self.MinerradioButton = QtWidgets.QRadioButton(self.frame_10)
        self.MinerradioButton.setGeometry(QtCore.QRect(160, 10, 51, 20))
        self.MinerradioButton.setObjectName("MinerradioButton")
        self.WalletAddressLabel = QtWidgets.QLabel(self.frame)
        self.WalletAddressLabel.setGeometry(QtCore.QRect(90, 30, 461, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WalletAddressLabel.setFont(font)
        self.WalletAddressLabel.setObjectName("WalletAddressLabel")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(550, 230, 51, 21))
        self.label_9.setObjectName("label_9")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(10, 230, 881, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.TransferWalletAddress = QtWidgets.QLineEdit(self.frame_11)
        self.TransferWalletAddress.setGeometry(QtCore.QRect(70, 10, 431, 21))
        self.TransferWalletAddress.setObjectName("TransferWalletAddress")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 51, 21))
        self.label_4.setObjectName("label_4")
        self.TransferCash = QtWidgets.QPushButton(self.frame_11)
        self.TransferCash.setGeometry(QtCore.QRect(770, 0, 101, 41))
        self.TransferCash.setObjectName("TransferCash")
        self.TransferValue = QtWidgets.QLineEdit(self.frame_11)
        self.TransferValue.setGeometry(QtCore.QRect(590, 10, 141, 21))
        self.TransferValue.setObjectName("TransferValue")
        self.frame_11.raise_()
        self.frame_10.raise_()
        self.GenerateA1.raise_()
        self.ValidatorradioButton.raise_()
        self.VDepositValue.raise_()
        self.label_3.raise_()
        self.WalletAddress.raise_()
        self.label_10.raise_()
        self.entrustAccount.raise_()
        self.CloseWallet.raise_()
        self.ConfirmWalletOP.raise_()
        self.OpenWallet.raise_()
        self.AutoCloseWallet.raise_()
        self.WalletAddressLabel.raise_()
        self.label_9.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(960, 20, 171, 191))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.DeployMinerNode = QtWidgets.QPushButton(self.frame_2)
        self.DeployMinerNode.setGeometry(QtCore.QRect(10, 40, 151, 51))
        self.DeployMinerNode.setObjectName("DeployMinerNode")
        self.ResetNode = QtWidgets.QPushButton(self.frame_2)
        self.ResetNode.setGeometry(QtCore.QRect(10, 101, 151, 41))
        self.ResetNode.setObjectName("ResetNode")
        self.NewNodeDepoly = QtWidgets.QPushButton(self.frame_2)
        self.NewNodeDepoly.setGeometry(QtCore.QRect(10, 1, 151, 41))
        self.NewNodeDepoly.setObjectName("NewNodeDepoly")
        self.StopNode = QtWidgets.QPushButton(self.frame_2)
        self.StopNode.setGeometry(QtCore.QRect(10, 141, 151, 41))
        self.StopNode.setObjectName("StopNode")
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(960, 230, 171, 141))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.CheckPunish = QtWidgets.QPushButton(self.frame_3)
        self.CheckPunish.setGeometry(QtCore.QRect(10, 100, 151, 32))
        self.CheckPunish.setObjectName("CheckPunish")
        self.CheckNodeConnection = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeConnection.setGeometry(QtCore.QRect(10, 70, 151, 32))
        self.CheckNodeConnection.setObjectName("CheckNodeConnection")
        self.CheckNodeSyncNTP = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeSyncNTP.setGeometry(QtCore.QRect(10, 40, 151, 32))
        self.CheckNodeSyncNTP.setObjectName("CheckNodeSyncNTP")
        self.CheckNodeSyncStatus = QtWidgets.QPushButton(self.frame_3)
        self.CheckNodeSyncStatus.setGeometry(QtCore.QRect(10, 10, 151, 32))
        self.CheckNodeSyncStatus.setObjectName("CheckNodeSyncStatus")
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        self.frame_4.setGeometry(QtCore.QRect(960, 380, 171, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.OpenExplorer = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorer.setGeometry(QtCore.QRect(10, 10, 151, 32))
        self.OpenExplorer.setObjectName("OpenExplorer")
        self.OpenExplorerWallet = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorerWallet.setGeometry(QtCore.QRect(10, 40, 151, 32))
        self.OpenExplorerWallet.setObjectName("OpenExplorerWallet")
        self.OpenExplorerAccount = QtWidgets.QPushButton(self.frame_4)
        self.OpenExplorerAccount.setGeometry(QtCore.QRect(10, 80, 151, 32))
        self.OpenExplorerAccount.setObjectName("OpenExplorerAccount")
        self.frame_5 = QtWidgets.QFrame(self.centralWidget)
        self.frame_5.setGeometry(QtCore.QRect(960, 520, 171, 141))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.DownloadTools = QtWidgets.QPushButton(self.frame_5)
        self.DownloadTools.setGeometry(QtCore.QRect(10, 0, 151, 32))
        self.DownloadTools.setObjectName("DownloadTools")
        self.CompileGAN = QtWidgets.QPushButton(self.frame_5)
        self.CompileGAN.setGeometry(QtCore.QRect(10, 40, 151, 32))
        self.CompileGAN.setObjectName("CompileGAN")
        self.CheckGMANVersion = QtWidgets.QPushButton(self.frame_5)
        self.CheckGMANVersion.setGeometry(QtCore.QRect(10, 70, 151, 32))
        self.CheckGMANVersion.setObjectName("CheckGMANVersion")
        self.UploadLog = QtWidgets.QPushButton(self.frame_5)
        self.UploadLog.setGeometry(QtCore.QRect(10, 110, 151, 32))
        self.UploadLog.setObjectName("UploadLog")
        self.frame_6 = QtWidgets.QFrame(self.centralWidget)
        self.frame_6.setGeometry(QtCore.QRect(20, 310, 921, 121))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 101, 20))
        self.label_7.setObjectName("label_7")
        self.listWidget = QtWidgets.QListWidget(self.frame_6)
        self.listWidget.setGeometry(QtCore.QRect(120, 50, 771, 61))
        self.listWidget.setObjectName("listWidget")
        self.cmdLogText = QtWidgets.QPlainTextEdit(self.frame_6)
        self.cmdLogText.setGeometry(QtCore.QRect(120, 10, 771, 31))
        self.cmdLogText.setObjectName("cmdLogText")
        self.frame_7 = QtWidgets.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(20, 440, 921, 381))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.NodeBootLogText = QtWidgets.QTextBrowser(self.frame_7)
        self.NodeBootLogText.setGeometry(QtCore.QRect(20, 30, 441, 341))
        self.NodeBootLogText.setObjectName("NodeBootLogText")
        self.NodeServiceText = QtWidgets.QTextBrowser(self.frame_7)
        self.NodeServiceText.setGeometry(QtCore.QRect(490, 30, 421, 341))
        self.NodeServiceText.setObjectName("NodeServiceText")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 20))
        self.label.setObjectName("label")
        self.NodeStartLogRefresh = QtWidgets.QPushButton(self.frame_7)
        self.NodeStartLogRefresh.setGeometry(QtCore.QRect(110, 0, 61, 32))
        self.NodeStartLogRefresh.setObjectName("NodeStartLogRefresh")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(470, 10, 111, 20))
        self.label_5.setObjectName("label_5")
        self.NodeServiceRefresh = QtWidgets.QPushButton(self.frame_7)
        self.NodeServiceRefresh.setGeometry(QtCore.QRect(580, 0, 61, 32))
        self.NodeServiceRefresh.setObjectName("NodeServiceRefresh")
        self.frame_8 = QtWidgets.QFrame(self.centralWidget)
        self.frame_8.setGeometry(QtCore.QRect(20, 830, 1111, 71))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.SetDefaultWorkDir = QtWidgets.QPushButton(self.frame_8)
        self.SetDefaultWorkDir.setGeometry(QtCore.QRect(20, 10, 81, 51))
        self.SetDefaultWorkDir.setObjectName("SetDefaultWorkDir")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(110, 30, 361, 20))
        self.label_8.setObjectName("label_8")
        self.UseDefaultA1Account = QtWidgets.QCheckBox(self.frame_8)
        self.UseDefaultA1Account.setGeometry(QtCore.QRect(510, 20, 21, 20))
        self.UseDefaultA1Account.setText("")
        self.UseDefaultA1Account.setObjectName("UseDefaultA1Account")
        self.NodeBootWalletAddress = QtWidgets.QLineEdit(self.frame_8)
        self.NodeBootWalletAddress.setGeometry(QtCore.QRect(510, 40, 571, 21))
        self.NodeBootWalletAddress.setObjectName("NodeBootWalletAddress")
        self.RandomAddressDescriptionLabel = QtWidgets.QLabel(self.frame_8)
        self.RandomAddressDescriptionLabel.setGeometry(QtCore.QRect(530, 20, 191, 20))
        self.RandomAddressDescriptionLabel.setObjectName("RandomAddressDescriptionLabel")
        self.frame_9 = QtWidgets.QFrame(self.centralWidget)
        self.frame_9.setGeometry(QtCore.QRect(960, 670, 171, 151))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.GenerateRandomAccountAddress = QtWidgets.QPushButton(self.frame_9)
        self.GenerateRandomAccountAddress.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.GenerateRandomAccountAddress.setObjectName("GenerateRandomAccountAddress")
        self.NodeInit = QtWidgets.QPushButton(self.frame_9)
        self.NodeInit.setGeometry(QtCore.QRect(10, 10, 151, 51))
        self.NodeInit.setObjectName("NodeInit")
        self.GenerateRandomAccountAddress_2 = QtWidgets.QPushButton(self.frame_9)
        self.GenerateRandomAccountAddress_2.setGeometry(QtCore.QRect(10, 100, 151, 41))
        self.GenerateRandomAccountAddress_2.setObjectName("GenerateRandomAccountAddress_2")
        self.frame.raise_()
        self.frame_9.raise_()
        self.frame_8.raise_()
        self.frame_7.raise_()
        self.frame_6.raise_()
        self.frame_3.raise_()
        self.frame_5.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MATRIX节点部署工具"))
        self.GenerateA1.setText(_translate("MainWindow", "无抵押账户？\n"
"生成一个账户"))
        self.ValidatorradioButton.setText(_translate("MainWindow", "验证者"))
        self.VDepositValue.setText(_translate("MainWindow", "验证者需高于10W"))
        self.label_3.setText(_translate("MainWindow", "钱包账户"))
        self.WalletAddress.setText(_translate("MainWindow", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.label_10.setText(_translate("MainWindow", "抵押对象"))
        self.entrustAccount.setText(_translate("MainWindow", "抵押账户（委托账户，当矿工和验证者节点需要使用该账户）填充，切勿输入私钥。"))
        self.CloseWallet.setText(_translate("MainWindow", "关闭钱包\n"
"(安全第一）"))
        self.ConfirmWalletOP.setText(_translate("MainWindow", "确定抵押\n"
"（节点需同步）"))
        self.OpenWallet.setText(_translate("MainWindow", "打开钱包\n"
"(会读取私钥）"))
        self.AutoCloseWallet.setText(_translate("MainWindow", "自动关闭钱包"))
        self.Current2Fixed.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Current2Fixed.setText(_translate("MainWindow", "活期转定期"))
        self.FollowSuperNode.setText(_translate("MainWindow", "追随他人\n"
"参加超级节点"))
        self.Fixed3MradioButton.setText(_translate("MainWindow", "3个月"))
        self.Fixed6MradioButton.setText(_translate("MainWindow", "6个月"))
        self.CurrentradioButton.setText(_translate("MainWindow", "活期"))
        self.Deposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Deposit.setText(_translate("MainWindow", "抵押"))
        self.DecreaseDeposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DecreaseDeposit.setText(_translate("MainWindow", "撤销抵押"))
        self.Fixed1MradioButton.setText(_translate("MainWindow", "1个月"))
        self.Fixed12Mradiobutton.setText(_translate("MainWindow", "12个月"))
        self.WorkAccount.setText(_translate("MainWindow", "输入参与的超级节点账户，请检查合法性（矿工和验证者最低为200MAN/1000MAN）"))
        self.CreateSuperNode.setText(_translate("MainWindow", "自己领头\n"
"建超级节点"))
        self.NormalNode.setText(_translate("MainWindow", "单干"))
        self.MDepositValue.setText(_translate("MainWindow", "矿工建议仅抵押1W"))
        self.MinerradioButton.setText(_translate("MainWindow", "矿工 "))
        self.WalletAddressLabel.setStatusTip(_translate("MainWindow", "请检查账户，谨慎操作"))
        self.WalletAddressLabel.setText(_translate("MainWindow", "当前钱包地址无效,不操作抵押、转账功能时，无需在本区域输入任何值"))
        self.label_9.setText(_translate("MainWindow", "转账金额"))
        self.TransferWalletAddress.setText(_translate("MainWindow", "请核对账户地址"))
        self.label_4.setText(_translate("MainWindow", "转账对象"))
        self.TransferCash.setText(_translate("MainWindow", "确定转账"))
        self.TransferValue.setText(_translate("MainWindow", "大额一定分批转"))
        self.DeployMinerNode.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DeployMinerNode.setText(_translate("MainWindow", "部署挖矿节点\n"
"(需指定抵押账户)"))
        self.ResetNode.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.ResetNode.setText(_translate("MainWindow", "手动重启节点"))
        self.NewNodeDepoly.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NewNodeDepoly.setText(_translate("MainWindow", "自动化部署观察节点"))
        self.StopNode.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.StopNode.setText(_translate("MainWindow", "节点停止工作"))
        self.CheckPunish.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckPunish.setText(_translate("MainWindow", "检查惩罚状态"))
        self.CheckNodeConnection.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeConnection.setText(_translate("MainWindow", "检查联通性"))
        self.CheckNodeSyncNTP.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeSyncNTP.setText(_translate("MainWindow", "检查时钟与NTP状态"))
        self.CheckNodeSyncStatus.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeSyncStatus.setText(_translate("MainWindow", "检查节点同步状态"))
        self.OpenExplorer.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorer.setText(_translate("MainWindow", "区块链浏览器预览"))
        self.OpenExplorerWallet.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorerWallet.setText(_translate("MainWindow", "在线钱包预览"))
        self.OpenExplorerAccount.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorerAccount.setText(_translate("MainWindow", "个人收益预览"))
        self.DownloadTools.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DownloadTools.setText(_translate("MainWindow", "下载必备工具到本地"))
        self.CompileGAN.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CompileGAN.setText(_translate("MainWindow", "手动编译GMAN"))
        self.CheckGMANVersion.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckGMANVersion.setText(_translate("MainWindow", "GMAN检查更新"))
        self.UploadLog.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.UploadLog.setText(_translate("MainWindow", "上传诊断日志"))
        self.label_6.setText(_translate("MainWindow", "执行的命令行："))
        self.label_7.setText(_translate("MainWindow", "命令历史记录："))
        self.label.setText(_translate("MainWindow", "节点启动结果"))
        self.NodeStartLogRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeStartLogRefresh.setText(_translate("MainWindow", "刷新"))
        self.label_5.setText(_translate("MainWindow", "节点服务状态日志"))
        self.NodeServiceRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeServiceRefresh.setText(_translate("MainWindow", "刷新"))
        self.SetDefaultWorkDir.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.SetDefaultWorkDir.setText(_translate("MainWindow", "修改默认\n"
"工作路径"))
        self.label_8.setText(_translate("MainWindow", "默认工作路径："))
        self.NodeBootWalletAddress.setText(_translate("MainWindow", "默认以抵押对象的名义启动，但我现在想换成这个账户启动，一定不要输入您资金所在的钱包账户"))
        self.RandomAddressDescriptionLabel.setText(_translate("MainWindow", "复制您生成的随机账户地址："))
        self.GenerateRandomAccountAddress.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.GenerateRandomAccountAddress.setText(_translate("MainWindow", "生成一个随机帐户"))
        self.NodeInit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeInit.setText(_translate("MainWindow", "节点初始化\n"
"（会去除部分数据）"))
        self.GenerateRandomAccountAddress_2.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.GenerateRandomAccountAddress_2.setText(_translate("MainWindow", "钱包对字符串签名"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
