# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liqinghua/eric/test2/MATRIXWallet.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 708)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(890, 10, 151, 32))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 130, 591, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 190, 371, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 160, 151, 20))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 300, 151, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(890, 50, 151, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(890, 250, 151, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 51, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 20, 591, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 81, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 90, 141, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton.setGeometry(QtCore.QRect(130, 60, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 90, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 60, 141, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 160, 61, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 100, 151, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(890, 150, 151, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_8.setGeometry(QtCore.QRect(380, 60, 151, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(890, 200, 151, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_10.setGeometry(QtCore.QRect(380, 90, 151, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(420, 160, 111, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_11.setGeometry(QtCore.QRect(530, 160, 61, 32))
        self.pushButton_11.setObjectName("pushButton_11")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(450, 190, 421, 371))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(60, 580, 361, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(460, 580, 361, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_12.setGeometry(QtCore.QRect(740, 10, 101, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setGeometry(QtCore.QRect(740, 60, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_13.setGeometry(QtCore.QRect(540, 60, 131, 61))
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(19, 19, 701, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_14.setGeometry(QtCore.QRect(890, 610, 151, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 600, 371, 74))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(460, 600, 411, 74))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(460, 680, 361, 20))
        self.label_8.setObjectName("label_8")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_15.setGeometry(QtCore.QRect(890, 650, 151, 32))
        self.pushButton_15.setObjectName("pushButton_15")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MATRIX节点部署工具"))
        self.pushButton.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton.setText(_translate("MainWindow", "部署全新节点"))
        self.lineEdit.setText(_translate("MainWindow", "A1账户名称，一定不要雨A0账户重合，如需要更高安全性，请启动A2账户"))
        self.label.setText(_translate("MainWindow", "节点启动结果"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_2.setText(_translate("MainWindow", "GMAN检查更新"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_3.setText(_translate("MainWindow", "重启节点"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_4.setText(_translate("MainWindow", "区块链浏览器预览"))
        self.label_2.setText(_translate("MainWindow", "工作账户"))
        self.label_3.setText(_translate("MainWindow", "钱包账户"))
        self.lineEdit_2.setText(_translate("MainWindow", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.label_4.setText(_translate("MainWindow", "准备抵押数额"))
        self.lineEdit_4.setText(_translate("MainWindow", "验证者需高于10W"))
        self.radioButton.setText(_translate("MainWindow", "矿工 "))
        self.radioButton_2.setText(_translate("MainWindow", "验证者"))
        self.lineEdit_5.setText(_translate("MainWindow", "矿工建议仅抵押1W"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_5.setText(_translate("MainWindow", "刷新"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_6.setText(_translate("MainWindow", "检查节点同步状态"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_7.setText(_translate("MainWindow", "检查联通性"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_8.setText(_translate("MainWindow", "抵押成为矿工或验证者"))
        self.pushButton_9.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_9.setText(_translate("MainWindow", "检查惩罚状态"))
        self.pushButton_10.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_10.setText(_translate("MainWindow", "降低抵押额或撤销抵押"))
        self.label_5.setText(_translate("MainWindow", "节点服务状态日志"))
        self.pushButton_11.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_11.setText(_translate("MainWindow", "刷新"))
        self.label_6.setText(_translate("MainWindow", "执行的命令行："))
        self.label_7.setText(_translate("MainWindow", "状态查询命令行："))
        self.pushButton_12.setText(_translate("MainWindow", "随时关闭钱包\n"
"(安全第一）"))
        self.checkBox.setText(_translate("MainWindow", "自动关闭钱包"))
        self.pushButton_13.setText(_translate("MainWindow", "确定对钱包的操作"))
        self.pushButton_14.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_14.setText(_translate("MainWindow", "手动编译GMAN"))
        self.label_8.setText(_translate("MainWindow", "默认工作路径："))
        self.pushButton_15.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.pushButton_15.setText(_translate("MainWindow", "修改默认工作路径"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
