# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liqinghua/eric/test2/MATRIXWallet.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 758)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.NewNodeDepoly = QtWidgets.QPushButton(self.centralWidget)
        self.NewNodeDepoly.setGeometry(QtCore.QRect(890, 20, 151, 32))
        self.NewNodeDepoly.setObjectName("NewNodeDepoly")
        self.WorkAccount = QtWidgets.QLineEdit(self.centralWidget)
        self.WorkAccount.setGeometry(QtCore.QRect(110, 150, 571, 21))
        self.WorkAccount.setObjectName("WorkAccount")
        self.NodeBootLogText = QtWidgets.QTextBrowser(self.centralWidget)
        self.NodeBootLogText.setGeometry(QtCore.QRect(30, 210, 371, 361))
        self.NodeBootLogText.setObjectName("NodeBootLogText")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 180, 81, 20))
        self.label.setObjectName("label")
        self.CheckGMANVersion = QtWidgets.QPushButton(self.centralWidget)
        self.CheckGMANVersion.setGeometry(QtCore.QRect(890, 680, 151, 32))
        self.CheckGMANVersion.setObjectName("CheckGMANVersion")
        self.ResetNode = QtWidgets.QPushButton(self.centralWidget)
        self.ResetNode.setGeometry(QtCore.QRect(890, 60, 151, 32))
        self.ResetNode.setObjectName("ResetNode")
        self.OpenExplorer = QtWidgets.QPushButton(self.centralWidget)
        self.OpenExplorer.setGeometry(QtCore.QRect(890, 370, 151, 32))
        self.OpenExplorer.setObjectName("OpenExplorer")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 51, 21))
        self.label_3.setObjectName("label_3")
        self.WalletAddress = QtWidgets.QLineEdit(self.centralWidget)
        self.WalletAddress.setGeometry(QtCore.QRect(90, 30, 591, 21))
        self.WalletAddress.setObjectName("WalletAddress")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 81, 21))
        self.label_4.setObjectName("label_4")
        self.VDepositValue = QtWidgets.QLineEdit(self.centralWidget)
        self.VDepositValue.setGeometry(QtCore.QRect(210, 100, 141, 21))
        self.VDepositValue.setObjectName("VDepositValue")
        self.MinerradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.MinerradioButton.setGeometry(QtCore.QRect(130, 70, 100, 20))
        self.MinerradioButton.setObjectName("MinerradioButton")
        self.ValidatorradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.ValidatorradioButton.setGeometry(QtCore.QRect(130, 100, 100, 20))
        self.ValidatorradioButton.setObjectName("ValidatorradioButton")
        self.MDepositValue = QtWidgets.QLineEdit(self.centralWidget)
        self.MDepositValue.setGeometry(QtCore.QRect(210, 70, 141, 21))
        self.MDepositValue.setObjectName("MDepositValue")
        self.NodeStartLogRefresh = QtWidgets.QPushButton(self.centralWidget)
        self.NodeStartLogRefresh.setGeometry(QtCore.QRect(120, 180, 61, 32))
        self.NodeStartLogRefresh.setObjectName("NodeStartLogRefresh")
        self.CheckNodeSyncStatus = QtWidgets.QPushButton(self.centralWidget)
        self.CheckNodeSyncStatus.setGeometry(QtCore.QRect(890, 210, 151, 32))
        self.CheckNodeSyncStatus.setObjectName("CheckNodeSyncStatus")
        self.CheckNodeConnection = QtWidgets.QPushButton(self.centralWidget)
        self.CheckNodeConnection.setGeometry(QtCore.QRect(890, 290, 151, 32))
        self.CheckNodeConnection.setObjectName("CheckNodeConnection")
        self.Deposit = QtWidgets.QPushButton(self.centralWidget)
        self.Deposit.setGeometry(QtCore.QRect(510, 60, 81, 41))
        self.Deposit.setObjectName("Deposit")
        self.CheckPunish = QtWidgets.QPushButton(self.centralWidget)
        self.CheckPunish.setGeometry(QtCore.QRect(890, 330, 151, 32))
        self.CheckPunish.setObjectName("CheckPunish")
        self.DecreaseDeposit = QtWidgets.QPushButton(self.centralWidget)
        self.DecreaseDeposit.setGeometry(QtCore.QRect(510, 100, 81, 41))
        self.DecreaseDeposit.setObjectName("DecreaseDeposit")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(420, 180, 111, 20))
        self.label_5.setObjectName("label_5")
        self.NodeServiceRefresh = QtWidgets.QPushButton(self.centralWidget)
        self.NodeServiceRefresh.setGeometry(QtCore.QRect(530, 180, 61, 32))
        self.NodeServiceRefresh.setObjectName("NodeServiceRefresh")
        self.NodeServiceText = QtWidgets.QTextBrowser(self.centralWidget)
        self.NodeServiceText.setGeometry(QtCore.QRect(450, 210, 421, 361))
        self.NodeServiceText.setObjectName("NodeServiceText")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(60, 590, 361, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(460, 590, 361, 20))
        self.label_7.setObjectName("label_7")
        self.CloseWallet = QtWidgets.QPushButton(self.centralWidget)
        self.CloseWallet.setGeometry(QtCore.QRect(740, 30, 101, 51))
        self.CloseWallet.setObjectName("CloseWallet")
        self.AutoCloseWallet = QtWidgets.QCheckBox(self.centralWidget)
        self.AutoCloseWallet.setGeometry(QtCore.QRect(730, 10, 101, 20))
        self.AutoCloseWallet.setObjectName("AutoCloseWallet")
        self.ConfirmWalletOP = QtWidgets.QPushButton(self.centralWidget)
        self.ConfirmWalletOP.setGeometry(QtCore.QRect(740, 80, 101, 51))
        self.ConfirmWalletOP.setObjectName("ConfirmWalletOP")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 831, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CompileGAN = QtWidgets.QPushButton(self.centralWidget)
        self.CompileGAN.setGeometry(QtCore.QRect(890, 650, 151, 32))
        self.CompileGAN.setObjectName("CompileGAN")
        self.cmdLogText = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.cmdLogText.setGeometry(QtCore.QRect(30, 610, 371, 74))
        self.cmdLogText.setObjectName("cmdLogText")
        self.StatusLogText = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.StatusLogText.setGeometry(QtCore.QRect(460, 610, 411, 74))
        self.StatusLogText.setObjectName("StatusLogText")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(460, 690, 361, 20))
        self.label_8.setObjectName("label_8")
        self.SetDefaultWorkDir = QtWidgets.QPushButton(self.centralWidget)
        self.SetDefaultWorkDir.setGeometry(QtCore.QRect(890, 590, 151, 32))
        self.SetDefaultWorkDir.setObjectName("SetDefaultWorkDir")
        self.CurrentradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.CurrentradioButton.setGeometry(QtCore.QRect(360, 70, 61, 20))
        self.CurrentradioButton.setObjectName("CurrentradioButton")
        self.Fixed1mradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.Fixed1mradioButton.setGeometry(QtCore.QRect(360, 90, 61, 20))
        self.Fixed1mradioButton.setObjectName("Fixed1mradioButton")
        self.Fixed3MradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.Fixed3MradioButton.setGeometry(QtCore.QRect(360, 110, 61, 20))
        self.Fixed3MradioButton.setObjectName("Fixed3MradioButton")
        self.Fixed6MradioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.Fixed6MradioButton.setGeometry(QtCore.QRect(430, 90, 61, 20))
        self.Fixed6MradioButton.setObjectName("Fixed6MradioButton")
        self.Fixed12Mradiobutton = QtWidgets.QRadioButton(self.centralWidget)
        self.Fixed12Mradiobutton.setGeometry(QtCore.QRect(430, 110, 61, 20))
        self.Fixed12Mradiobutton.setObjectName("Fixed12Mradiobutton")
        self.Current2Fixed = QtWidgets.QPushButton(self.centralWidget)
        self.Current2Fixed.setGeometry(QtCore.QRect(600, 70, 91, 51))
        self.Current2Fixed.setObjectName("Current2Fixed")
        self.DownloadTools = QtWidgets.QPushButton(self.centralWidget)
        self.DownloadTools.setGeometry(QtCore.QRect(890, 620, 151, 32))
        self.DownloadTools.setObjectName("DownloadTools")
        self.ResetNode_2 = QtWidgets.QPushButton(self.centralWidget)
        self.ResetNode_2.setGeometry(QtCore.QRect(740, 150, 101, 32))
        self.ResetNode_2.setObjectName("ResetNode_2")
        self.OpenExplorer_2 = QtWidgets.QPushButton(self.centralWidget)
        self.OpenExplorer_2.setGeometry(QtCore.QRect(890, 410, 151, 32))
        self.OpenExplorer_2.setObjectName("OpenExplorer_2")
        self.OpenExplorer_3 = QtWidgets.QPushButton(self.centralWidget)
        self.OpenExplorer_3.setGeometry(QtCore.QRect(890, 450, 151, 32))
        self.OpenExplorer_3.setObjectName("OpenExplorer_3")
        self.CheckNodeSyncStatus_2 = QtWidgets.QPushButton(self.centralWidget)
        self.CheckNodeSyncStatus_2.setGeometry(QtCore.QRect(890, 250, 151, 32))
        self.CheckNodeSyncStatus_2.setObjectName("CheckNodeSyncStatus_2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MATRIX节点部署工具"))
        self.NewNodeDepoly.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NewNodeDepoly.setText(_translate("MainWindow", "部署全新节点"))
        self.WorkAccount.setText(_translate("MainWindow", "A1账户名称，一定不要与A0账户重合，如需要更高安全性，请启动A2账户"))
        self.label.setText(_translate("MainWindow", "节点启动结果"))
        self.CheckGMANVersion.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckGMANVersion.setText(_translate("MainWindow", "GMAN检查更新"))
        self.ResetNode.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.ResetNode.setText(_translate("MainWindow", "重启节点"))
        self.OpenExplorer.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorer.setText(_translate("MainWindow", "区块链浏览器预览"))
        self.label_2.setText(_translate("MainWindow", "工作账户"))
        self.label_3.setText(_translate("MainWindow", "钱包账户"))
        self.WalletAddress.setText(_translate("MainWindow", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.label_4.setText(_translate("MainWindow", "准备抵押数额"))
        self.VDepositValue.setText(_translate("MainWindow", "验证者需高于10W"))
        self.MinerradioButton.setText(_translate("MainWindow", "矿工 "))
        self.ValidatorradioButton.setText(_translate("MainWindow", "验证者"))
        self.MDepositValue.setText(_translate("MainWindow", "矿工建议仅抵押1W"))
        self.NodeStartLogRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeStartLogRefresh.setText(_translate("MainWindow", "刷新"))
        self.CheckNodeSyncStatus.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeSyncStatus.setText(_translate("MainWindow", "检查节点同步状态"))
        self.CheckNodeConnection.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeConnection.setText(_translate("MainWindow", "检查联通性"))
        self.Deposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Deposit.setText(_translate("MainWindow", "抵押"))
        self.CheckPunish.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckPunish.setText(_translate("MainWindow", "检查惩罚状态"))
        self.DecreaseDeposit.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DecreaseDeposit.setText(_translate("MainWindow", "撤销抵押"))
        self.label_5.setText(_translate("MainWindow", "节点服务状态日志"))
        self.NodeServiceRefresh.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.NodeServiceRefresh.setText(_translate("MainWindow", "刷新"))
        self.label_6.setText(_translate("MainWindow", "执行的命令行："))
        self.label_7.setText(_translate("MainWindow", "状态查询命令行："))
        self.CloseWallet.setText(_translate("MainWindow", "关闭钱包\n"
"(安全第一）"))
        self.AutoCloseWallet.setText(_translate("MainWindow", "自动关闭钱包"))
        self.ConfirmWalletOP.setText(_translate("MainWindow", "确定\n"
"对钱包的操作"))
        self.CompileGAN.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CompileGAN.setText(_translate("MainWindow", "手动编译GMAN"))
        self.label_8.setText(_translate("MainWindow", "默认工作路径："))
        self.SetDefaultWorkDir.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.SetDefaultWorkDir.setText(_translate("MainWindow", "修改默认工作路径"))
        self.CurrentradioButton.setText(_translate("MainWindow", "活期"))
        self.Fixed1mradioButton.setText(_translate("MainWindow", "1个月"))
        self.Fixed3MradioButton.setText(_translate("MainWindow", "3个月"))
        self.Fixed6MradioButton.setText(_translate("MainWindow", "6个月"))
        self.Fixed12Mradiobutton.setText(_translate("MainWindow", "12个月"))
        self.Current2Fixed.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.Current2Fixed.setText(_translate("MainWindow", "活期转定期"))
        self.DownloadTools.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.DownloadTools.setText(_translate("MainWindow", "下载必备工具到本地"))
        self.ResetNode_2.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.ResetNode_2.setText(_translate("MainWindow", "配置工作账户"))
        self.OpenExplorer_2.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorer_2.setText(_translate("MainWindow", "在线钱包预览"))
        self.OpenExplorer_3.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.OpenExplorer_3.setText(_translate("MainWindow", "个人收益预览"))
        self.CheckNodeSyncStatus_2.setToolTip(_translate("MainWindow", "生成命令行，并启动节点"))
        self.CheckNodeSyncStatus_2.setText(_translate("MainWindow", "检查时钟与NTP状态"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
