# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liqinghua/eric/test2/MATRIXNodeMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1075, 673)
        TabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.wallet = QtWidgets.QWidget()
        self.wallet.setObjectName("wallet")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wallet)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MainAccountLabel = QtWidgets.QLabel(self.wallet)
        self.MainAccountLabel.setObjectName("MainAccountLabel")
        self.gridLayout_2.addWidget(self.MainAccountLabel, 0, 0, 1, 1)
        self.TransferHash = QtWidgets.QLabel(self.wallet)
        self.TransferHash.setObjectName("TransferHash")
        self.gridLayout_2.addWidget(self.TransferHash, 5, 5, 1, 1)
        self.WebStatusLabel = QtWidgets.QLabel(self.wallet)
        self.WebStatusLabel.setObjectName("WebStatusLabel")
        self.gridLayout_2.addWidget(self.WebStatusLabel, 6, 0, 1, 2)
        self.OpenOnlineWallet = QtWidgets.QPushButton(self.wallet)
        self.OpenOnlineWallet.setObjectName("OpenOnlineWallet")
        self.gridLayout_2.addWidget(self.OpenOnlineWallet, 6, 3, 1, 2)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.wallet)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.gridLayout_2.addWidget(self.webEngineView, 7, 0, 1, 6)
        self.CurrentAccountStatusLabel = QtWidgets.QLabel(self.wallet)
        self.CurrentAccountStatusLabel.setObjectName("CurrentAccountStatusLabel")
        self.gridLayout_2.addWidget(self.CurrentAccountStatusLabel, 1, 0, 1, 3)
        self.TransferAccountLabel = QtWidgets.QLabel(self.wallet)
        self.TransferAccountLabel.setObjectName("TransferAccountLabel")
        self.gridLayout_2.addWidget(self.TransferAccountLabel, 1, 4, 1, 1)
        self.CurrentAccountLog = QtWidgets.QTextBrowser(self.wallet)
        self.CurrentAccountLog.setObjectName("CurrentAccountLog")
        self.gridLayout_2.addWidget(self.CurrentAccountLog, 3, 0, 3, 4)
        self.CloseWallet = QtWidgets.QPushButton(self.wallet)
        self.CloseWallet.setObjectName("CloseWallet")
        self.gridLayout_2.addWidget(self.CloseWallet, 6, 2, 1, 1)
        self.TransferCashNumLabel = QtWidgets.QLabel(self.wallet)
        self.TransferCashNumLabel.setObjectName("TransferCashNumLabel")
        self.gridLayout_2.addWidget(self.TransferCashNumLabel, 4, 4, 1, 1)
        self.WalletAddress = QtWidgets.QLineEdit(self.wallet)
        self.WalletAddress.setObjectName("WalletAddress")
        self.gridLayout_2.addWidget(self.WalletAddress, 0, 1, 1, 4)
        self.openKeystore = QtWidgets.QPushButton(self.wallet)
        self.openKeystore.setObjectName("openKeystore")
        self.gridLayout_2.addWidget(self.openKeystore, 0, 5, 1, 1)
        self.TransferCash2Account = QtWidgets.QPlainTextEdit(self.wallet)
        self.TransferCash2Account.setObjectName("TransferCash2Account")
        self.gridLayout_2.addWidget(self.TransferCash2Account, 3, 4, 1, 1)
        self.TransferCashNum = QtWidgets.QPlainTextEdit(self.wallet)
        self.TransferCashNum.setObjectName("TransferCashNum")
        self.gridLayout_2.addWidget(self.TransferCashNum, 5, 4, 1, 1)
        self.ConfirmTransfer2others = QtWidgets.QPushButton(self.wallet)
        self.ConfirmTransfer2others.setObjectName("ConfirmTransfer2others")
        self.gridLayout_2.addWidget(self.ConfirmTransfer2others, 3, 5, 1, 1)
        TabWidget.addTab(self.wallet, "")
        self.Node = QtWidgets.QWidget()
        self.Node.setObjectName("Node")
        self.NewNodeDepoly = QtWidgets.QPushButton(self.Node)
        self.NewNodeDepoly.setGeometry(QtCore.QRect(890, 40, 151, 32))
        self.NewNodeDepoly.setObjectName("NewNodeDepoly")
        self.ResetNode = QtWidgets.QPushButton(self.Node)
        self.ResetNode.setGeometry(QtCore.QRect(890, 170, 151, 32))
        self.ResetNode.setObjectName("ResetNode")
        self.NodeServiceText = QtWidgets.QTextBrowser(self.Node)
        self.NodeServiceText.setGeometry(QtCore.QRect(460, 40, 421, 551))
        self.NodeServiceText.setObjectName("NodeServiceText")
        self.NodeBootLogText = QtWidgets.QTextBrowser(self.Node)
        self.NodeBootLogText.setGeometry(QtCore.QRect(20, 40, 411, 311))
        self.NodeBootLogText.setObjectName("NodeBootLogText")
        self.CheckNodeSyncNTP = QtWidgets.QPushButton(self.Node)
        self.CheckNodeSyncNTP.setGeometry(QtCore.QRect(890, 250, 151, 32))
        self.CheckNodeSyncNTP.setObjectName("CheckNodeSyncNTP")
        self.CheckNodeSyncStatus = QtWidgets.QPushButton(self.Node)
        self.CheckNodeSyncStatus.setGeometry(QtCore.QRect(890, 210, 151, 32))
        self.CheckNodeSyncStatus.setObjectName("CheckNodeSyncStatus")
        self.CheckNodeConnection = QtWidgets.QPushButton(self.Node)
        self.CheckNodeConnection.setGeometry(QtCore.QRect(890, 290, 151, 32))
        self.CheckNodeConnection.setObjectName("CheckNodeConnection")
        self.OpenExplorer = QtWidgets.QPushButton(self.Node)
        self.OpenExplorer.setGeometry(QtCore.QRect(890, 430, 151, 32))
        self.OpenExplorer.setObjectName("OpenExplorer")
        self.CheckPunish = QtWidgets.QPushButton(self.Node)
        self.CheckPunish.setGeometry(QtCore.QRect(890, 330, 151, 32))
        self.CheckPunish.setObjectName("CheckPunish")
        self.NodeInit = QtWidgets.QPushButton(self.Node)
        self.NodeInit.setGeometry(QtCore.QRect(890, 510, 151, 32))
        self.NodeInit.setObjectName("NodeInit")
        self.DownloadProgramfromOfficial = QtWidgets.QPushButton(self.Node)
        self.DownloadProgramfromOfficial.setGeometry(QtCore.QRect(890, 470, 151, 32))
        self.DownloadProgramfromOfficial.setObjectName("DownloadProgramfromOfficial")
        self.cmdLineLabel = QtWidgets.QLabel(self.Node)
        self.cmdLineLabel.setGeometry(QtCore.QRect(20, 10, 361, 20))
        self.cmdLineLabel.setObjectName("cmdLineLabel")
        self.cmdLineResultLabel = QtWidgets.QLabel(self.Node)
        self.cmdLineResultLabel.setGeometry(QtCore.QRect(460, 10, 361, 20))
        self.cmdLineResultLabel.setObjectName("cmdLineResultLabel")
        self.NodeStatusLabel = QtWidgets.QLabel(self.Node)
        self.NodeStatusLabel.setGeometry(QtCore.QRect(20, 380, 361, 20))
        self.NodeStatusLabel.setObjectName("NodeStatusLabel")
        self.NodeStatus = QtWidgets.QTextBrowser(self.Node)
        self.NodeStatus.setGeometry(QtCore.QRect(20, 400, 411, 191))
        self.NodeStatus.setObjectName("NodeStatus")
        self.NodeBootWalletAddress = QtWidgets.QLineEdit(self.Node)
        self.NodeBootWalletAddress.setGeometry(QtCore.QRect(520, 620, 491, 21))
        self.NodeBootWalletAddress.setObjectName("NodeBootWalletAddress")
        self.AutoCloseWalletCheckBox_2 = QtWidgets.QCheckBox(self.Node)
        self.AutoCloseWalletCheckBox_2.setGeometry(QtCore.QRect(490, 620, 21, 20))
        self.AutoCloseWalletCheckBox_2.setText("")
        self.AutoCloseWalletCheckBox_2.setObjectName("AutoCloseWalletCheckBox_2")
        self.GenerateRandomAccountAddress = QtWidgets.QPushButton(self.Node)
        self.GenerateRandomAccountAddress.setGeometry(QtCore.QRect(890, 540, 151, 71))
        self.GenerateRandomAccountAddress.setObjectName("GenerateRandomAccountAddress")
        self.RandomAddressDescriptionLabel = QtWidgets.QLabel(self.Node)
        self.RandomAddressDescriptionLabel.setGeometry(QtCore.QRect(520, 600, 151, 20))
        self.RandomAddressDescriptionLabel.setObjectName("RandomAddressDescriptionLabel")
        self.RandomAccountLabel = QtWidgets.QLabel(self.Node)
        self.RandomAccountLabel.setGeometry(QtCore.QRect(670, 600, 391, 20))
        self.RandomAccountLabel.setObjectName("RandomAccountLabel")
        self.NewNodeDepoly_2 = QtWidgets.QPushButton(self.Node)
        self.NewNodeDepoly_2.setGeometry(QtCore.QRect(890, 80, 151, 32))
        self.NewNodeDepoly_2.setObjectName("NewNodeDepoly_2")
        TabWidget.addTab(self.Node, "")
        self.SuperNode = QtWidgets.QWidget()
        self.SuperNode.setToolTipDuration(5)
        self.SuperNode.setObjectName("SuperNode")
        self.CloseSuperNodeWallet = QtWidgets.QPushButton(self.SuperNode)
        self.CloseSuperNodeWallet.setGeometry(QtCore.QRect(890, 20, 161, 51))
        self.CloseSuperNodeWallet.setObjectName("CloseSuperNodeWallet")
        self.MDepositValue = QtWidgets.QLineEdit(self.SuperNode)
        self.MDepositValue.setGeometry(QtCore.QRect(330, 180, 141, 21))
        self.MDepositValue.setObjectName("MDepositValue")
        self.VDepositValue = QtWidgets.QLineEdit(self.SuperNode)
        self.VDepositValue.setGeometry(QtCore.QRect(330, 230, 141, 21))
        self.VDepositValue.setObjectName("VDepositValue")
        self.SuperNodeAccount = QtWidgets.QLineEdit(self.SuperNode)
        self.SuperNodeAccount.setGeometry(QtCore.QRect(140, 20, 481, 21))
        self.SuperNodeAccount.setObjectName("SuperNodeAccount")
        self.AutoCloseWalletCheckBox = QtWidgets.QCheckBox(self.SuperNode)
        self.AutoCloseWalletCheckBox.setGeometry(QtCore.QRect(900, 70, 101, 20))
        self.AutoCloseWalletCheckBox.setObjectName("AutoCloseWalletCheckBox")
        self.ValidatorradioButton = QtWidgets.QRadioButton(self.SuperNode)
        self.ValidatorradioButton.setGeometry(QtCore.QRect(250, 230, 100, 20))
        self.ValidatorradioButton.setObjectName("ValidatorradioButton")
        self.MinerradioButton = QtWidgets.QRadioButton(self.SuperNode)
        self.MinerradioButton.setGeometry(QtCore.QRect(250, 180, 100, 20))
        self.MinerradioButton.setObjectName("MinerradioButton")
        self.label_9 = QtWidgets.QLabel(self.SuperNode)
        self.label_9.setGeometry(QtCore.QRect(70, 20, 51, 21))
        self.label_9.setObjectName("label_9")
        self.entrustAccount = QtWidgets.QLineEdit(self.SuperNode)
        self.entrustAccount.setGeometry(QtCore.QRect(140, 80, 481, 21))
        self.entrustAccount.setObjectName("entrustAccount")
        self.label_10 = QtWidgets.QLabel(self.SuperNode)
        self.label_10.setGeometry(QtCore.QRect(70, 80, 51, 21))
        self.label_10.setObjectName("label_10")
        self.GenerateA1 = QtWidgets.QPushButton(self.SuperNode)
        self.GenerateA1.setGeometry(QtCore.QRect(690, 70, 161, 51))
        self.GenerateA1.setObjectName("GenerateA1")
        self.openSuperNodeKeystore = QtWidgets.QPushButton(self.SuperNode)
        self.openSuperNodeKeystore.setGeometry(QtCore.QRect(690, 20, 161, 51))
        self.openSuperNodeKeystore.setObjectName("openSuperNodeKeystore")
        self.StandloneNode = QtWidgets.QRadioButton(self.SuperNode)
        self.StandloneNode.setGeometry(QtCore.QRect(70, 180, 100, 31))
        self.StandloneNode.setObjectName("StandloneNode")
        self.SuperNodeCmd = QtWidgets.QTextBrowser(self.SuperNode)
        self.SuperNodeCmd.setGeometry(QtCore.QRect(20, 380, 411, 241))
        self.SuperNodeCmd.setObjectName("SuperNodeCmd")
        self.executeCmdLabel = QtWidgets.QLabel(self.SuperNode)
        self.executeCmdLabel.setGeometry(QtCore.QRect(20, 350, 361, 20))
        self.executeCmdLabel.setObjectName("executeCmdLabel")
        self.SuperNodeLog = QtWidgets.QTextBrowser(self.SuperNode)
        self.SuperNodeLog.setGeometry(QtCore.QRect(460, 380, 411, 241))
        self.SuperNodeLog.setObjectName("SuperNodeLog")
        self.executeCmdResultLabel = QtWidgets.QLabel(self.SuperNode)
        self.executeCmdResultLabel.setGeometry(QtCore.QRect(480, 350, 361, 20))
        self.executeCmdResultLabel.setObjectName("executeCmdResultLabel")
        self.ViewSynchronousStatus = QtWidgets.QPushButton(self.SuperNode)
        self.ViewSynchronousStatus.setGeometry(QtCore.QRect(890, 150, 161, 51))
        self.ViewSynchronousStatus.setObjectName("ViewSynchronousStatus")
        self.NodeStatusLabel_2 = QtWidgets.QLabel(self.SuperNode)
        self.NodeStatusLabel_2.setGeometry(QtCore.QRect(900, 210, 171, 20))
        self.NodeStatusLabel_2.setObjectName("NodeStatusLabel_2")
        self.DepositDescriptionLabel = QtWidgets.QLabel(self.SuperNode)
        self.DepositDescriptionLabel.setGeometry(QtCore.QRect(70, 130, 271, 21))
        self.DepositDescriptionLabel.setObjectName("DepositDescriptionLabel")
        self.frame_2 = QtWidgets.QFrame(self.SuperNode)
        self.frame_2.setGeometry(QtCore.QRect(20, 120, 841, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(40, 40, 131, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.CreateSuperNode = QtWidgets.QRadioButton(self.frame_3)
        self.CreateSuperNode.setGeometry(QtCore.QRect(10, 60, 100, 51))
        self.CreateSuperNode.setObjectName("CreateSuperNode")
        self.attendSuperNode = QtWidgets.QRadioButton(self.frame_3)
        self.attendSuperNode.setGeometry(QtCore.QRect(10, 110, 100, 61))
        self.attendSuperNode.setObjectName("attendSuperNode")
        self.CurrentradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.CurrentradioButton.setGeometry(QtCore.QRect(470, 50, 61, 20))
        self.CurrentradioButton.setObjectName("CurrentradioButton")
        self.Fixed12Mradiobutton = QtWidgets.QRadioButton(self.frame_2)
        self.Fixed12Mradiobutton.setGeometry(QtCore.QRect(540, 110, 61, 20))
        self.Fixed12Mradiobutton.setObjectName("Fixed12Mradiobutton")
        self.Fixed6MradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.Fixed6MradioButton.setGeometry(QtCore.QRect(540, 80, 61, 20))
        self.Fixed6MradioButton.setObjectName("Fixed6MradioButton")
        self.Fixed1mradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.Fixed1mradioButton.setGeometry(QtCore.QRect(470, 80, 61, 20))
        self.Fixed1mradioButton.setObjectName("Fixed1mradioButton")
        self.Fixed3MradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.Fixed3MradioButton.setGeometry(QtCore.QRect(470, 110, 61, 20))
        self.Fixed3MradioButton.setObjectName("Fixed3MradioButton")
        self.AttendSupernodeAccount = QtWidgets.QLineEdit(self.frame_2)
        self.AttendSupernodeAccount.setGeometry(QtCore.QRect(200, 170, 501, 21))
        self.AttendSupernodeAccount.setObjectName("AttendSupernodeAccount")
        self.ConfirmDeposit = QtWidgets.QPushButton(self.frame_2)
        self.ConfirmDeposit.setGeometry(QtCore.QRect(670, 30, 161, 51))
        self.ConfirmDeposit.setObjectName("ConfirmDeposit")
        self.Current2Fixed = QtWidgets.QPushButton(self.frame_2)
        self.Current2Fixed.setGeometry(QtCore.QRect(670, 110, 91, 51))
        self.Current2Fixed.setObjectName("Current2Fixed")
        self.DecreaseDeposit = QtWidgets.QPushButton(self.frame_2)
        self.DecreaseDeposit.setGeometry(QtCore.QRect(750, 110, 81, 51))
        self.DecreaseDeposit.setObjectName("DecreaseDeposit")
        self.frame_2.raise_()
        self.CloseSuperNodeWallet.raise_()
        self.MDepositValue.raise_()
        self.VDepositValue.raise_()
        self.SuperNodeAccount.raise_()
        self.AutoCloseWalletCheckBox.raise_()
        self.ValidatorradioButton.raise_()
        self.MinerradioButton.raise_()
        self.label_9.raise_()
        self.entrustAccount.raise_()
        self.label_10.raise_()
        self.GenerateA1.raise_()
        self.openSuperNodeKeystore.raise_()
        self.StandloneNode.raise_()
        self.SuperNodeCmd.raise_()
        self.executeCmdLabel.raise_()
        self.SuperNodeLog.raise_()
        self.executeCmdResultLabel.raise_()
        self.ViewSynchronousStatus.raise_()
        self.NodeStatusLabel_2.raise_()
        self.DepositDescriptionLabel.raise_()
        TabWidget.addTab(self.SuperNode, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.webEngineViewMainnet = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.webEngineViewMainnet.setUrl(QtCore.QUrl("https://kfc.matrix.io/home"))
        self.webEngineViewMainnet.setObjectName("webEngineViewMainnet")
        self.gridLayout.addWidget(self.webEngineViewMainnet, 0, 0, 1, 1)
        TabWidget.addTab(self.tab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "MATRIX节点部署与状态监测"))
        self.MainAccountLabel.setText(_translate("TabWidget", "钱包账户"))
        self.TransferHash.setText(_translate("TabWidget", "转账结果与Hash"))
        self.WebStatusLabel.setText(_translate("TabWidget", "网页访问状态"))
        self.OpenOnlineWallet.setText(_translate("TabWidget", "开启在线钱包，注意保存私钥，防止黑客"))
        self.CurrentAccountStatusLabel.setText(_translate("TabWidget", "查询当前账户状态"))
        self.TransferAccountLabel.setText(_translate("TabWidget", "给某个账户转账："))
        self.CloseWallet.setText(_translate("TabWidget", "关闭钱包，然后访问账户状态网页"))
        self.TransferCashNumLabel.setText(_translate("TabWidget", "给账户转账金额："))
        self.WalletAddress.setText(_translate("TabWidget", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.openKeystore.setText(_translate("TabWidget", "打开本地钱包keystore操作"))
        self.ConfirmTransfer2others.setText(_translate("TabWidget", "给别人转账"))
        TabWidget.setTabText(TabWidget.indexOf(self.wallet), _translate("TabWidget", "账户设置"))
        self.NewNodeDepoly.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.NewNodeDepoly.setText(_translate("TabWidget", "全自动部署全新节点"))
        self.ResetNode.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.ResetNode.setText(_translate("TabWidget", "重启节点"))
        self.CheckNodeSyncNTP.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.CheckNodeSyncNTP.setText(_translate("TabWidget", "检查时钟与NTP状态"))
        self.CheckNodeSyncStatus.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.CheckNodeSyncStatus.setText(_translate("TabWidget", "检查节点同步状态"))
        self.CheckNodeConnection.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.CheckNodeConnection.setText(_translate("TabWidget", "检查联通性"))
        self.OpenExplorer.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.OpenExplorer.setText(_translate("TabWidget", "区块链浏览器预览"))
        self.CheckPunish.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.CheckPunish.setText(_translate("TabWidget", "检查惩罚状态"))
        self.NodeInit.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.NodeInit.setText(_translate("TabWidget", "节点初始化"))
        self.DownloadProgramfromOfficial.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.DownloadProgramfromOfficial.setText(_translate("TabWidget", "从官方下载程序"))
        self.cmdLineLabel.setText(_translate("TabWidget", "执行的命令行："))
        self.cmdLineResultLabel.setText(_translate("TabWidget", "当前命令执行结果"))
        self.NodeStatusLabel.setText(_translate("TabWidget", "节点通用状态显示"))
        self.NodeBootWalletAddress.setText(_translate("TabWidget", "以这个账户的名义启动，一定不要输入钱包账户"))
        self.GenerateRandomAccountAddress.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.GenerateRandomAccountAddress.setText(_translate("TabWidget", "生成一个随机帐户\n"
"            用于启动节点\n"
"        "))
        self.RandomAddressDescriptionLabel.setText(_translate("TabWidget", "您生成的随机账户地址是："))
        self.RandomAccountLabel.setText(_translate("TabWidget", "MAN."))
        self.NewNodeDepoly_2.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.NewNodeDepoly_2.setText(_translate("TabWidget", "配置后再起节点"))
        TabWidget.setTabText(TabWidget.indexOf(self.Node), _translate("TabWidget", "普通节点监测"))
        self.CloseSuperNodeWallet.setText(_translate("TabWidget", "关闭钱包\n"
"   (安全第一)"))
        self.MDepositValue.setText(_translate("TabWidget", "矿工建议仅抵押1W"))
        self.VDepositValue.setText(_translate("TabWidget", "验证者需高于10W"))
        self.SuperNodeAccount.setText(_translate("TabWidget", "MAN账户钱包地址填充，切勿输入私钥。"))
        self.AutoCloseWalletCheckBox.setText(_translate("TabWidget", "自动关闭钱包"))
        self.ValidatorradioButton.setText(_translate("TabWidget", "验证者"))
        self.MinerradioButton.setText(_translate("TabWidget", "矿工"))
        self.label_9.setText(_translate("TabWidget", "钱包账户"))
        self.entrustAccount.setText(_translate("TabWidget", "抵押账户（委托账户，节点需要使用该账户）填充，切勿输入私钥。"))
        self.label_10.setText(_translate("TabWidget", "抵押对象"))
        self.GenerateA1.setText(_translate("TabWidget", "没有A1账户？\n"
"帮您生成一个委托账户"))
        self.openSuperNodeKeystore.setText(_translate("TabWidget", "打开钱包"))
        self.StandloneNode.setText(_translate("TabWidget", "单干\n"
"            自己起节点\n"
"        "))
        self.executeCmdLabel.setText(_translate("TabWidget", "执行的命令行："))
        self.executeCmdResultLabel.setText(_translate("TabWidget", "执行的结果："))
        self.ViewSynchronousStatus.setText(_translate("TabWidget", "查看同步状态\n"
"（建议同步后再抵押）"))
        self.NodeStatusLabel_2.setText(_translate("TabWidget", "当前同步情况："))
        self.DepositDescriptionLabel.setText(_translate("TabWidget", "抵押金额与抵押方式设置"))
        self.CreateSuperNode.setText(_translate("TabWidget", "自己领头\n"
"                    建超级节点\n"
"                "))
        self.attendSuperNode.setText(_translate("TabWidget", "追随他人\n"
"                    加入超级节点\n"
"                "))
        self.CurrentradioButton.setText(_translate("TabWidget", "活期"))
        self.Fixed12Mradiobutton.setText(_translate("TabWidget", "12个月"))
        self.Fixed6MradioButton.setText(_translate("TabWidget", "6个月"))
        self.Fixed1mradioButton.setText(_translate("TabWidget", "1个月"))
        self.Fixed3MradioButton.setText(_translate("TabWidget", "3个月"))
        self.AttendSupernodeAccount.setText(_translate("TabWidget", "输入参与的超级节点账户，请检查合法性（矿工和验证者最低为200MAN/1000MAN）"))
        self.ConfirmDeposit.setText(_translate("TabWidget", "确认抵押\n"
"                   （谨慎操作)\n"
"               "))
        self.Current2Fixed.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.Current2Fixed.setText(_translate("TabWidget", "活期转定期"))
        self.DecreaseDeposit.setToolTip(_translate("TabWidget", "生成命令行，并启动节点"))
        self.DecreaseDeposit.setText(_translate("TabWidget", "撤销抵押"))
        TabWidget.setTabText(TabWidget.indexOf(self.SuperNode), _translate("TabWidget", "超级节点配置与运行"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "MATRIX主网状态"))


from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
